name: "Build and cache nix dev environment"

on:
  push:
    branches:
      - main

jobs:
  devenv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: famisoft
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: |
        nix develop --print-build-logs --accept-flake-config --impure --command true
